version: 1.0
# kubectl -n openfaas port-forward svc/gateway-external 31112:8080
provider:
  name: openfaas
  gateway: http://127.0.0.1:31112
functions:
  ping-pong:
    lang: java8
    handler: ./ping-pong
    image: hbouvier/function-ping-pong-java8:latest
